doctor/doctor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    path('turn/', include('turn.urls', namespace='turn')),
    ]

doctor/turn/urls.py
from django.urls import path
from .views import CreateAppointmentsView,ReserveAppointmentView,doctor_delay_view,ReservedAppointments_listView
app_name='turn'
urlpatterns = [
    # ...
    path('create/', CreateAppointmentsView.as_view(), name='create_appointment'),
    path('reserved_appointments/', ReserveAppointmentView.as_view(), name='reserved_appointments'),
    path('delay/', doctor_delay_view.as_view(), name='doctor_delay'),
    path('reserved_list/',ReservedAppointments_listView.as_view(), name='reserved_list'),
    # ...
    # ...
]

doctor/turn/models.py
from django.db import models
from datetime import timedelta,datetime
from django.contrib.auth import get_user_model
# Create your models here.

class Doctor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def create_appointments(self, start_date, end_date, start_time, end_time):
        current_date = start_date
        current_time = datetime.combine(datetime.min.date(), start_time)

        while current_date <= end_date:
            while current_time.time() < end_time:
                appointment_start = datetime.combine(current_date, current_time.time())
                appointment_end = appointment_start + timedelta(minutes=20)
                appointment = Appointment(doctor=self, start_date=current_date, end_date=current_date,
                                          start_time=appointment_start.time(), end_time=appointment_end.time())
                appointment.save()
                current_time += timedelta(minutes=20)

            current_date += timedelta(days=1)
            current_time = datetime.combine(datetime.min.date(), start_time)



class Appointment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f"Appointment with {self.doctor} from {self.start_date} {self.start_time} to {self.end_date} {self.end_time}"

doctor/turn/forms.py
from django import forms
from .models import Doctor,Appointment

class AppointmentForm(forms.ModelForm):
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all())

    class Meta:
        model = Appointment
        fields = ['doctor', 'start_date', 'end_date','start_time', 'end_time']

class DoctorDelayForm(forms.Form):
    delay_time = forms.IntegerField(label='Delay Time')

doctor/turn/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import Doctor, Appointment
from datetime import datetime, timedelta
from .forms import DoctorDelayForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
class CreateAppointmentsView(View):
    def get(self, request):
        doctors = Doctor.objects.all()
        return render(request, 'create_appointment.html', {'doctors': doctors})

    def post(self, request):
        doctor_id = request.POST.get('doctor')
        start_date = datetime.strptime(request.POST.get('start_date'), '%Y-%m-%d').date()
        end_date = datetime.strptime(request.POST.get('end_date'), '%Y-%m-%d').date()
        start_time = datetime.strptime(request.POST.get('start_time'), '%H:%M').time()
        end_time = datetime.strptime(request.POST.get('end_time'), '%H:%M').time()

        doctor = Doctor.objects.get(id=doctor_id)
        doctor.create_appointments(start_date, end_date, start_time, end_time)

        return render(request, 'appointment_success.html')

@method_decorator(login_required, name='dispatch')
class ReserveAppointmentView(View):
    def get(self, request):
        appointments = Appointment.objects.filter(is_reserved=False)

        return render(request, 'reserved_appointments.html', {'appointments': appointments})

    def post(self, request):
        appointment_id = request.POST.get('appointment_id')
        print(appointment_id)
        appointment = Appointment.objects.get(id=appointment_id)
        appointment.user = request.user
        print(appointment.user)
        appointment.is_reserved = True
        appointment.save()
        return redirect('turn:reserved_appointments')

class doctor_delay_view(View):
    def get(self, request):
        form = DoctorDelayForm()
        return render(request, 'doctor_delay.html', {'form': form})

    def post(self, request):
        form = DoctorDelayForm(request.POST)
        if form.is_valid():
            delay_time = form.cleaned_data['delay_time']
            appointments = Appointment.objects.filter(doctor=request.user)
            for appointment in appointments:
                appointment.start_time += timedelta(minutes=delay_time)
                appointment.end_time += timedelta(minutes=delay_time)
                appointment.save()
            return redirect('turn:reserved_appointments')
        return render(request, 'doctor_delay.html', {'form': form})

class ReservedAppointments_listView(View):
    def get(self, request):
        user = request.user
        appointments = Appointment.objects.filter(is_reserved=True)
        return render(request, 'reserved_appoint_list.html', {'appointments': appointments})

doctor/turn/templates/appointment_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>سلام</title>
</head>
<body>

</body>
</html>

doctor/turn/templates/create_appointment.html
<h1>Create Appointment</h1>
<form method="POST" action="{% url 'turn:create_appointment' %}">
    {% csrf_token %}
  <label for="id_doctor">Doctor:</label>
  <select name="doctor" id="id_doctor">
    {% for doctor in doctors %}
      <option value="{{ doctor.id }}">{{ doctor.name }}</option>
    {% endfor %}
  </select>
  <br>
  <label for="id_start_date">Start Date:</label>
  <input type="date" name="start_date" id="id_start_date">
  <br>
  <label for="id_end_date">End Date:</label>
  <input type="date" name="end_date" id="id_end_date">
  <br>
  <label for="id_start_time">Start Time:</label>
  <input type="time" name="start_time" id="id_start_time">
  <br>
  <label for="id_end_time">End Time:</label>
  <input type="time" name="end_time" id="id_end_time">
  <br>
  <button type="submit">Create</button>
</form>

doctor/turn/templates/doctor_delay.html
<!-- doctor_delay.html -->
<h1>Doctor Delay</h1>
<form method="POST" action="{% url 'turn:doctor_delay' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

doctor/turn/templates/reserved_appoint_list.html
<h1>Reserved Appointments</h1>
<ul>
  {% for appointment in appointments %}
    <li>{{ appointment }}</li>
      <li>{{ appointment.user }}</li>

  {% empty %}
    <li>No reserved appointments.</li>
  {% endfor %}
</ul>

doctor/turn/templates/reserved_appointments.html
<h1>Choose an Available Appointment</h1>
<form method="POST" action="{% url 'turn:reserved_appointments' %}">
  {% csrf_token %}
  <ul>
    {% for appointment in appointments %}
      <li>
        <input type="radio" name="appointment_id" value="{{ appointment.id }}">
        <label>{{ appointment }}</label>
        <span>Doctor Delay: {{ appointment.doctor_delay|default:"Not Set" }}</span>
      </li>
    {% empty %}
      <li>No available appointments.</li>
    {% endfor %}
  </ul>
  <button type="submit">Reserve</button>
</form>